- name: Import generated image into Incus
  ansible.builtin.command:
    argv:
      - incus
      - image
      - import
      - "{{ incus_windows_metadata_path }}"
      - "{{ incus_windows_disk_path }}"
      - requirements.cdrom_agent=true
      - --alias
      - "{{ incus_windows_import_alias }}"
  changed_when: true
